apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
spec:
  containers:
  - name: main-app
    image: nginx:1.14
    ports:
    - containerPort: 80
    securityContext:
      privileged: true
    env:
    - name: APP_SECRET
      value: "hardcodedsecret"
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
  - name: sidecar-logger
    image: busybox
    command: ["/bin/sh", "-c", "while true; do cat /var/log/nginx/access.log; sleep 10; done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    securityContext:
      runAsUser: 0
  volumes:
  - name: shared-logs
    emptyDir: {}